# SPDX-License-Identifier: MIT
# terraform: language=hcl
# workers.tf - Cloudflare Workers managed via Terraform
#
# This deploys Workers with their code and secrets in a single apply.
# Worker code lives in cloudflare/workers/<name>/.

# =============================================================================
# Vault Data Sources for Worker Secrets
# =============================================================================

# Discord webhook URL for HCP Terraform notifications
data "vault_kv_secret_v2" "discord_webhook" {
  mount = "secret"
  name  = "fzymgc-house/infrastructure/cloudflare/discord-webhook"
}

# HMAC secret for HCP Terraform notification signature verification
# Generated by tf/vault using random_password resource
data "vault_kv_secret_v2" "hcp_terraform_hmac" {
  mount = "secret"
  name  = "fzymgc-house/infrastructure/cloudflare/hcp-terraform-hmac"
}

# =============================================================================
# HCP Terraform Discord Notification Worker
# =============================================================================

# The Worker resource defines persistent settings (name, tags)
resource "cloudflare_worker" "hcp_terraform_discord" {
  account_id = var.cloudflare_account_id
  name       = "hcp-terraform-discord"
  tags       = ["terraform", "notifications", "discord"]
}

# The Worker version deploys code + bindings (Python Worker)
resource "cloudflare_worker_version" "hcp_terraform_discord" {
  account_id          = var.cloudflare_account_id
  worker_id           = cloudflare_worker.hcp_terraform_discord.id
  compatibility_date  = "2025-12-01"
  compatibility_flags = ["python_workers"]
  main_module         = "worker.py"

  modules = [
    {
      name         = "worker.py"
      content_type = "text/x-python"
      content_file = "${path.module}/../../cloudflare/workers/hcp-terraform-discord/worker.py"
    },
    {
      name         = "requirements.txt"
      content_type = "text/x-python-requirement"
      content_file = "${path.module}/../../cloudflare/workers/hcp-terraform-discord/requirements.txt"
    }
  ]

  bindings = [
    {
      type = "secret_text"
      name = "DISCORD_WEBHOOK_URL"
      text = data.vault_kv_secret_v2.discord_webhook.data["url"]
    },
    {
      type = "secret_text"
      name = "HMAC_SECRET"
      text = data.vault_kv_secret_v2.hcp_terraform_hmac.data["token"]
    }
  ]

  lifecycle {
    create_before_destroy = true
  }
}

# Deploy the version to production
resource "cloudflare_workers_deployment" "hcp_terraform_discord" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.hcp_terraform_discord.name
  strategy    = "percentage"

  versions = [
    {
      version_id = cloudflare_worker_version.hcp_terraform_discord.id
      percentage = 100
    }
  ]
}

# Custom domain for the Worker (avoids workers.dev subdomain dependency)
# Using fzymgc.net for external webhooks (avoids split-horizon DNS with fzymgc.house)
resource "cloudflare_workers_custom_domain" "hcp_terraform_discord" {
  account_id = var.cloudflare_account_id
  hostname   = "hcp-tf${var.webhook_suffix}.${var.webhook_domain}"
  service    = cloudflare_worker.hcp_terraform_discord.name
  zone_id    = data.cloudflare_zone.fzymgc_net.id
}

# =============================================================================
# Store Worker URL in Vault for tf/hcp-terraform to consume
# =============================================================================

# Store the Worker URL so tf/hcp-terraform can configure notifications
resource "vault_kv_secret_v2" "hcp_terraform_worker" {
  mount = "secret"
  name  = "fzymgc-house/infrastructure/cloudflare/hcp-terraform-worker"

  data_json = jsonencode({
    url = "https://${cloudflare_workers_custom_domain.hcp_terraform_discord.hostname}"
  })

  custom_metadata {
    max_versions = 5
    data = {
      managed_by = "terraform"
      module     = "tf/cloudflare"
    }
  }
}
