# SPDX-License-Identifier: MIT
# terraform: language=hcl
# workers.tf - Cloudflare Workers managed via Terraform
#
# This deploys Workers with their code and secrets in a single apply.
# Worker code lives in cloudflare/workers/<name>/.

# =============================================================================
# Vault Data Sources for Worker Secrets
# =============================================================================

# Discord webhook URL for HCP Terraform notifications
data "vault_kv_secret_v2" "discord_webhook" {
  mount = "secret"
  name  = "fzymgc-house/infrastructure/cloudflare/discord-webhook"
}

# HMAC secret for HCP Terraform notification signature verification
# Generated by tf/vault using random_password resource
data "vault_kv_secret_v2" "hcp_terraform_hmac" {
  mount = "secret"
  name  = "fzymgc-house/infrastructure/cloudflare/hcp-terraform-hmac"
}

# =============================================================================
# HCP Terraform Discord Notification Worker
# =============================================================================

# The Worker resource defines persistent settings (name, tags)
resource "cloudflare_worker" "hcp_terraform_discord" {
  account_id = var.cloudflare_account_id
  name       = "hcp-terraform-discord"
  tags       = ["terraform", "notifications", "discord"]
}

# The Worker version deploys code + bindings
# Worker URL: https://hcp-terraform-discord.<workers-subdomain>.workers.dev
# The workers.dev subdomain is configured in Cloudflare dashboard, not the account ID
resource "cloudflare_worker_version" "hcp_terraform_discord" {
  account_id         = var.cloudflare_account_id
  worker_id          = cloudflare_worker.hcp_terraform_discord.id
  compatibility_date = "2025-12-01"
  main_module        = "worker.js"

  modules = [{
    name         = "worker.js"
    content_type = "application/javascript+module"
    content_file = "${path.module}/../../cloudflare/workers/hcp-terraform-discord/worker.js"
  }]

  bindings = [
    {
      type = "secret_text"
      name = "DISCORD_WEBHOOK_URL"
      text = data.vault_kv_secret_v2.discord_webhook.data["url"]
    },
    {
      type = "secret_text"
      name = "HMAC_SECRET"
      text = data.vault_kv_secret_v2.hcp_terraform_hmac.data["token"]
    }
  ]

  lifecycle {
    create_before_destroy = true
  }
}

# Deploy the version to production
resource "cloudflare_workers_deployment" "hcp_terraform_discord" {
  account_id  = var.cloudflare_account_id
  script_name = cloudflare_worker.hcp_terraform_discord.name
  strategy    = "percentage"

  versions = [
    {
      version_id = cloudflare_worker_version.hcp_terraform_discord.id
      percentage = 100
    }
  ]
}
