// secrets-cloudflare.tf - Secrets for Cloudflare Worker integrations
//
// These secrets are generated by Terraform and stored in Vault for
// consumption by other modules (e.g., tf/cloudflare).

# HMAC token for HCP Terraform webhook signature verification
# Used by hcp-terraform-discord Cloudflare Worker to validate requests
resource "random_password" "hcp_terraform_hmac" {
  length  = 64
  special = false
}

resource "vault_kv_secret_v2" "hcp_terraform_hmac" {
  mount = "secret"
  name  = "fzymgc-house/infrastructure/cloudflare/hcp-terraform-hmac"

  data_json = jsonencode({
    token = random_password.hcp_terraform_hmac.result
  })

  lifecycle {
    ignore_changes = [data_json]
  }
}
